# Generated by Django 5.2.4 on 2025-08-09 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=5, verbose_name='Тема')),
                ('ai_personality', models.TextField(blank=True, verbose_name='Личность AI')),
                ('ai_model', models.CharField(choices=[('chatgpt', 'ChatGPT'), ('claude', 'Claude'), ('perplexity', 'Perplexity')], default='chatgpt', max_length=10, verbose_name='Модель AI')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=4, verbose_name='Тарифный план')),
                ('ai_descriptions_used', models.IntegerField(default=0, verbose_name='Использовано описаний AI')),
                ('ai_chat_requests_used', models.IntegerField(default=0, verbose_name='Использовано запросов чата AI')),
                ('ai_usage_last_reset', models.DateField(auto_now_add=True, verbose_name='Последний сброс лимитов AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
