# Generated by Django 5.2.4 on 2025-08-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anthropic_api_key',
            field=models.TextField(blank=True, verbose_name='Anthropic API ключ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_key',
            field=models.TextField(blank=True, verbose_name='OpenAI API ключ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perplexity_api_key',
            field=models.TextField(blank=True, verbose_name='Perplexity API ключ'),
        ),
    ]
