# Generated by Django 5.2.4 on 2025-08-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='perplexity_api_key',
        ),
    ]
